#!/usr/bin/env node

/**
 * Setup script for LLM Observability Monitor
 * Helps users configure real vs mock implementations
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('🚀 LLM Observability Monitor Setup\n');
  
  const setupType = await question(
    'Choose setup type:\n' +
    '1. Real implementation (requires Google Cloud & Datadog credentials)\n' +
    '2. Development/Mock setup (no credentials required)\n' +
    'Enter choice (1 or 2): '
  );

  let envContent = '';
  
  if (setupType === '1') {
    console.log('\n📋 Setting up real implementation...\n');
    
    const projectId = await question('Google Cloud Project ID: ');
    const location = await question('Google Cloud Location (default: us-central1): ') || 'us-central1';
    const credentialsPath = await question('Path to service account JSON (default: ./credentials/gcp-service-account.json): ') || './credentials/gcp-service-account.json';
    
    const datadogApiKey = await question('Datadog API Key: ');
    const datadogAppKey = await question('Datadog App Key: ');
    const datadogSite = await question('Datadog Site (default: datadoghq.com): ') || 'datadoghq.com';
    
    const appName = await question('Application Name (default: llm-observability-monitor): ') || 'llm-observability-monitor';
    const environment = await question('Environment (development/staging/production, default: development): ') || 'development';
    
    envContent = `# LLM Observability Monitor - Real Implementation Configuration
# Generated by setup script

# ============================================================================
# Google Cloud Configuration
# ============================================================================
GOOGLE_CLOUD_PROJECT_ID=${projectId}
GOOGLE_CLOUD_LOCATION=${location}
GOOGLE_APPLICATION_CREDENTIALS=${credentialsPath}

# ============================================================================
# Datadog Configuration
# ============================================================================
DATADOG_API_KEY=${datadogApiKey}
DATADOG_APP_KEY=${datadogAppKey}
DATADOG_SITE=${datadogSite}

# ============================================================================
# Application Configuration
# ============================================================================
APP_NAME=${appName}
APP_VERSION=1.0.0
APP_ENVIRONMENT=${environment}
NODE_ENV=${environment}

# ============================================================================
# Real Implementation Settings
# ============================================================================
USE_REAL_VERTEX_AI=true
USE_REAL_DATADOG=true
USE_REAL_DLP=true

# ============================================================================
# Telemetry Configuration
# ============================================================================
TELEMETRY_BATCH_SIZE=100
TELEMETRY_FLUSH_INTERVAL=5000
TELEMETRY_MAX_RETRIES=3
TELEMETRY_RETRY_DELAY=1000

# ============================================================================
# Security Configuration
# ============================================================================
SECURITY_ENABLE_DLP=true
SECURITY_CONFIDENCE_THRESHOLD=0.8

# ============================================================================
# Cost Configuration
# ============================================================================
COST_CURRENCY=USD

# ============================================================================
# Logging Configuration
# ============================================================================
LOG_LEVEL=info
DEBUG=llm-monitor:*

# ============================================================================
# Development Configuration
# ============================================================================
ENABLE_MOCK_FALLBACK=true
ENABLE_VERBOSE_LOGGING=false
ENABLE_TELEMETRY_DUMP=false
`;

  } else if (setupType === '2') {
    console.log('\n🛠️ Setting up development/mock configuration...\n');
    
    const appName = await question('Application Name (default: llm-observability-monitor): ') || 'llm-observability-monitor';
    
    envContent = `# LLM Observability Monitor - Development/Mock Configuration
# Generated by setup script

# ============================================================================
# Google Cloud Configuration (Mock)
# ============================================================================
GOOGLE_CLOUD_PROJECT_ID=mock-project-id
GOOGLE_CLOUD_LOCATION=us-central1
GOOGLE_APPLICATION_CREDENTIALS=./mock-credentials.json

# ============================================================================
# Datadog Configuration (Mock)
# ============================================================================
DATADOG_API_KEY=mock-datadog-api-key
DATADOG_APP_KEY=mock-datadog-app-key
DATADOG_SITE=datadoghq.com

# ============================================================================
# Application Configuration
# ============================================================================
APP_NAME=${appName}
APP_VERSION=1.0.0
APP_ENVIRONMENT=development
NODE_ENV=development

# ============================================================================
# Mock Implementation Settings
# ============================================================================
USE_REAL_VERTEX_AI=false
USE_REAL_DATADOG=false
USE_REAL_DLP=false

# ============================================================================
# Telemetry Configuration
# ============================================================================
TELEMETRY_BATCH_SIZE=10
TELEMETRY_FLUSH_INTERVAL=2000
TELEMETRY_MAX_RETRIES=2
TELEMETRY_RETRY_DELAY=500

# ============================================================================
# Security Configuration
# ============================================================================
SECURITY_ENABLE_DLP=false
SECURITY_CONFIDENCE_THRESHOLD=0.7

# ============================================================================
# Cost Configuration
# ============================================================================
COST_CURRENCY=USD

# ============================================================================
# Logging Configuration
# ============================================================================
LOG_LEVEL=debug
DEBUG=llm-monitor:*

# ============================================================================
# Development Configuration
# ============================================================================
ENABLE_MOCK_FALLBACK=true
ENABLE_VERBOSE_LOGGING=true
ENABLE_TELEMETRY_DUMP=true
`;

  } else {
    console.log('❌ Invalid choice. Exiting...');
    rl.close();
    return;
  }

  // Write .env file
  fs.writeFileSync('.env', envContent);
  console.log('\n✅ Configuration written to .env file');
  
  if (setupType === '1') {
    console.log('\n📝 Next steps for real implementation:');
    console.log('1. Ensure your Google Cloud service account has the following permissions:');
    console.log('   - Vertex AI User');
    console.log('   - Cloud DLP User');
    console.log('   - Service Account Token Creator (if using default credentials)');
    console.log('2. Enable the following APIs in Google Cloud Console:');
    console.log('   - Vertex AI API');
    console.log('   - Cloud DLP API');
    console.log('3. Verify your Datadog API and App keys have the required permissions');
    console.log('4. Run: npm install');
    console.log('5. Run: npm run build');
    console.log('6. Run: npm start');
  } else {
    console.log('\n📝 Next steps for development setup:');
    console.log('1. Run: npm install');
    console.log('2. Run: npm run build');
    console.log('3. Run: npm run dev');
    console.log('4. The system will use mock implementations for testing');
  }
  
  console.log('\n🎉 Setup complete! Check the README.md for more information.');
  rl.close();
}

main().catch(console.error);